import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "./ThemeRegistry";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "DigitalSE",
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<ThemeRegistry options={{ key: "mui" }}>
					<Navbar />
					{children}
					<Footer />
				</ThemeRegistry>
			</body>
		</html>
	);
}
