name: Build and Deploy Application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIGITAL_SE_CMS_ENDPOINT: ${{ secrets.DIGITAL_SE_CMS_ENDPOINT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET }}/
